version: '3'
services:
  dpkg-viewer-client:
    # build: .
    image: "karek/dpkg-viewer-client"
    ports:
      - "8080:80"
    depends_on:
      - "dpkg-viewer-server"
  dpkg-viewer-server:
    image: "karek/dpkg-viewer-server"
    ports:
      - "8081:8081"